title: Conversational UI
baseURL: https://marekmalik.github.io/conversational-ui/
languageCode: cs-cz
publishDir: docs
googleAnalytics: UA-117947191-1

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Marek Malík, Kryštof Davídek, Matouš Přibyl

